### PR TITLE
upgrades collectd to 5.5.0

### PR DESCRIPTION
**Pull request by sherzberg**
a tag for this would be awesome as well

### CODE REVIEW

**Comment by fr3nd** [comment]
thanks! :+1:

**Comment by sherzberg** [comment]
No problem. When you get a chance, can you setup a 5.5.0 tag in the docker hub? Thanks!

**Comment by fr3nd** [comment]
It's already there ;)

**Comment by sherzberg** [comment]
Oh nice, I must have just refreshed the hub page too late. Thank you!

**Pull request merged**
